DROP TABLE IF EXISTS paypal;
CREATE TABLE paypal (
  ddate DATETIME,
  dtime TIME,
  time_zone VARCHAR(5) NOT NULL COMMENT 'Abbreviation of time zone',
  first_last_name VARCHAR(255) NULL COMMENT 'First and last name',
  type VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL,
  currency CHAR(3) NOT NULL,
  gross DECIMAL(20, 2) NOT NULL,
  fee DECIMAL(20, 2) NOT NULL,
  net DECIMAL(20, 2) NOT NULL,
  from_email VARCHAR(255) NULL,
  to_email VARCHAR(255) NULL,
  transaction_id VARCHAR(24) NOT NULL,
  shipping_address VARCHAR(255) NULL,
  address_status VARCHAR(24) NULL,
  item_title VARCHAR(255) NULL,
  item_id VARCHAR(255) NULL,
  shipping_amount DECIMAL(20, 2) NULL,
  insurance_amount DECIMAL(20, 2) NULL,
  sales_tax DECIMAL(20, 2) NULL,
  option_1_name VARCHAR(255) NULL,
  option_1_value VARCHAR(255) NULL,
  option_2_name VARCHAR(255) NULL,
  option_2_value VARCHAR(255) NULL,
  reference_txn_id VARCHAR(255) NULL,
  invoice_number VARCHAR(255) NULL,
  custom_number VARCHAR(255) NULL,
  quantity INT NULL,
  receipt_id VARCHAR(255) NULL,
  balance DECIMAL(20, 2) NOT NULL,
  address_line_1 VARCHAR(255) NULL,
  address_line_2 VARCHAR(255) NULL,
  city VARCHAR(255) NULL,
  state VARCHAR(255) NULL,
  postal_code VARCHAR(255) NULL,
  country VARCHAR(255) NULL,
  phone_number VARCHAR(255) NULL,
  subject VARCHAR(255) NULL,
  note VARCHAR(255) NULL,
  country_code CHAR(2) NULL,
  balance_impact VARCHAR(255) NULL
);
