DROP TABLE IF EXISTS bank;
CREATE TABLE bank (
  id1 INT UNSIGNED,
  id2 INT UNSIGNED,
  id3 VARCHAR(32),
  operation_date DATETIME,
  record_date DATETIME,
  subject VARCHAR(255) NULL,
  group_id INT UNSIGNED,
  amount DECIMAL(20, 2) NOT NULL,
  direction CHAR(1) NOT NULL COMMENT 'c - credit (minus), d - debit (plus)',
  first_last_name VARCHAR(255) NULL COMMENT 'First and last name',
  bic VARCHAR(32) NOT NULL,
  iban VARCHAR(32) NOT NULL,
  text1 VARCHAR(255) NULL,
  text2 VARCHAR(255) NULL,
  text3 VARCHAR(255) NULL,
  text4 VARCHAR(255) NULL,
  text5 VARCHAR(255) NULL,
  text6 VARCHAR(255) NULL,
  text7 VARCHAR(255) NULL,
  text8 VARCHAR(255) NULL,
  text9 VARCHAR(255) NULL,
  text10 VARCHAR(255) NULL,
  text11 VARCHAR(255) NULL,
  text12 VARCHAR(255) NULL,
  text13 VARCHAR(255) NULL,
  text14 VARCHAR(255) NULL,
  text15 VARCHAR(255) NULL,
  text_merged TEXT NOT NULL,
  source VARCHAR(10) DEFAULT 'bank' COMMENT 'stripe, paypal, sepa, bank'
);
